"""Render the README a labeler opens with the package.

Ported from the vault workflow's ``generate_readme.py`` (talmolab/sleap-roots-training#26;
Box copy 2026-08-03), behavior preserved. Reads ``sample_manifest.csv`` and the curated
``images/`` directory and writes the package's ``README.md``.

**This file is the faithful port.** Everything crop-specific in it is hardcoded — the
title, the Bloom experiment id, the accession map, the two skeleton descriptions, the
project filenames — because the vault script was hand-edited per package (design.md F7).
The counts are derived two different ways from two different sources, neither of which is
the manifest's own record of what should be there. Task 8.3a is the commit that replaces
all of it with a render of the 8.3 metadata record; this commit exists so that what was
replaced is on the record first (design.md Decision 1).

The labeler-facing content — the SLEAP install links, the Notion guide, the ``v000``/
``v001`` versioning convention — is good documentation and is not crop-specific, so it
survives the deviation unchanged.
"""

from __future__ import annotations

import csv
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

README_TEMPLATE = """\
# Soybean WEEP Labeling Package

## What Is This?

This package contains curated soybean images from the WEEP experiment with
model-predicted root landmarks. Your task is to review and correct these
predictions in SLEAP to build better training data.

## Getting Started

1. **Install SLEAP** on your GPU laptop: [sleap.ai installation (pip/uv)](https://sleap.ai/installation)
2. **Read the SLEAP tutorial**: [sleap.ai tutorial](https://sleap.ai/tutorials/tutorial.html)
3. **Read our labeling guide**: [SLEAP Labeling and SLEAP GUI](https://www.notion.so/1224a67a766780da8b64c8cab59939b2) (Notion -- has soybean-specific labeling rules with PowerPoints)

## Package Contents

| File | Description |
|------|-------------|
| `images/` | {image_count} curated JPG images from WEEP soybean experiment |
| `soybean_weep_primary_labels.v000.slp` | Primary root predictions (6 nodes: r1-r6) |
| `soybean_weep_lateral_labels.v000.slp` | Lateral root predictions (4 nodes: r1-r4) |
| `sample_manifest.csv` | Metadata for selected images (plant ID, age, accession, view) |
| `README.md` | This file |

## How to Open in SLEAP

1. Open SLEAP GUI: `sleap-label`
2. File -> Open Project -> select `soybean_weep_primary_labels.v000.slp`
3. The images should load automatically from the `images/` folder
4. Predictions appear as overlays on each frame -- these are starting points

## About the Predictions

The predictions were generated by our standard soybean models. They appear as
**predicted instances** (visually distinct from user-confirmed labels in SLEAP).

## Versioning Convention

- `v000` = model predictions (this package, do not modify)
- `v001` = your first pass of corrections (Save As with new version)
- `v002`, `v003` ... = subsequent rounds

**Always Save As a new version** -- don't overwrite v000 so we can compare.

## Skeleton Reference

**Primary root** (6 nodes): `r1` (base/seed) -> `r2` -> `r3` -> `r4` -> `r5` -> `r6` (tip)

**Lateral root** (4 nodes): `r1` (base/attachment) -> `r2` -> `r3` -> `r4` (tip)

Nodes should be **evenly spaced** along the root. `r1` is always the base.

## Data Source

- Bloom experiment: WEEP_Soybean (ID 10102496)
- {plant_count} plants sampled across ages: {ages}
- Accessions: {accessions}
- {views_per_plant} rotational views per plant
- Total images: {image_count}
- QC-filtered: only well-germinated samples included
"""


def generate_readme(
    manifest_csv: Path,
    images_dir: Path,
    output_path: Path,
) -> None:
    """Generate ``README.md`` from manifest data.

    Args:
        manifest_csv: Path to ``sample_manifest.csv``.
        images_dir: Path to the curated ``images/`` directory.
        output_path: Path to write ``README.md``.
    """
    with open(manifest_csv) as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    accession_map = {
        "12742739": "A3244",
        "12742740": "WEEP-1-4",
        "12742741": "WEEP-1-1",
    }

    image_count = len(list(images_dir.glob("*.jpg")))
    plant_count = len(set(r["plant_qr_code"] for r in rows))
    ages = sorted(set(int(r["plant_age_days"]) for r in rows))
    accession_ids = sorted(set(r["accession_id"] for r in rows))
    accessions = ", ".join(accession_map.get(a, a) for a in accession_ids)
    views_per_plant = len(rows) // plant_count if plant_count else 0

    readme = README_TEMPLATE.format(
        image_count=image_count,
        plant_count=plant_count,
        ages=", ".join(f"{a} DAG" for a in ages),
        accessions=accessions,
        views_per_plant=views_per_plant,
    )

    output_path.write_text(readme)
    logger.info("Wrote README to %s", output_path)
