"""Render the README a labeler opens with the package.

Ported from the vault workflow's ``generate_readme.py`` (talmolab/sleap-roots-training#26;
Box copy 2026-08-03). The faithful port is this file's first commit; task 8.3a is the
deviation, and it changes where the content comes from rather than what it says.

The vault script held the crop, the experiment, the Bloom experiment id, the accession
names, the project filenames and the skeleton node counts as hardcoded text, edited by hand
per package (design.md F7). That put the skeleton description in a second copy alongside
``build_slp_project.py``'s constants with nothing keeping them in step, and it made the
Bloom trace — which ``#10``'s ``LabelCard`` needs — an English sentence. Everything now
renders from :class:`~sleap_roots_training.labeling.metadata.PackageRecord` and the
manifest, so the README is a *view* of the package's metadata rather than a second,
hand-synced statement of it.

The labeler-facing content is unchanged: the SLEAP install and tutorial links, the Notion
labeling guide, and the ``v000``/``v001`` versioning convention are good documentation and
are not crop-specific.
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from sleap_roots_training.labeling.metadata import (
    PACKAGE_METADATA_FILENAME,
    PackageRecord,
    read_package_metadata,
)
from sleap_roots_training.labeling.validate import (
    IMAGES_DIRNAME,
    MANIFEST_FILENAME,
    assert_counts_agree,
    project_filename,
)

logger = logging.getLogger(__name__)

README_FILENAME = "README.md"

_PREAMBLE = """\
# {title}

## What Is This?

This package contains curated {species} images from the {experiment} experiment with
model-predicted root landmarks. Your task is to review and correct these
predictions in SLEAP to build better training data.

## Getting Started

1. **Install SLEAP** on your GPU laptop: [sleap.ai installation (pip/uv)](https://sleap.ai/installation)
2. **Read the SLEAP tutorial**: [sleap.ai tutorial](https://sleap.ai/tutorials/tutorial.html)
3. **Read our labeling guide**: [SLEAP Labeling and SLEAP GUI](https://www.notion.so/1224a67a766780da8b64c8cab59939b2) (Notion -- labeling rules and PowerPoints)

## Package Contents

| File | Description |
|------|-------------|
| `{images_dirname}/` | {image_count} curated JPG images from the {experiment} {species} experiment |
{project_rows}| `{manifest_filename}` | Metadata for selected images (plant ID, age, accession, view) |
| `{metadata_filename}` | Package identity, selection parameters, and skeletons |
| `{readme_filename}` | This file |

## How to Open in SLEAP

1. Open SLEAP GUI: `sleap-label`
2. File -> Open Project -> select `{first_project}`
3. The images should load automatically -- they are embedded in the project file
4. Predictions appear as overlays on each frame -- these are starting points

## About the Predictions

The predictions were generated by our standard {species} models. They appear as
**predicted instances** (visually distinct from user-confirmed labels in SLEAP).

## Versioning Convention

- `v000` = model predictions (this package, do not modify)
- `v001` = your first pass of corrections (Save As with new version)
- `v002`, `v003` ... = subsequent rounds

**Always Save As a new version** -- don't overwrite v000 so we can compare.

## Skeleton Reference

{skeleton_reference}

Nodes should be **evenly spaced** along the root. `r1` is always the base.

## Data Source

- Bloom experiment ID: {bloom_experiment_id}
- {plant_count} plants sampled across ages: {ages}
- Accessions: {accessions}
- {views_per_plant} rotational views per plant
- Total images: {image_count}
- QC-filtered: only well-germinated samples included

## Selection Parameters

Recorded so this package can be re-derived and widened rather than edited in place. See
`{metadata_filename}` for the machine-readable copy.

- Seed: {seed}
- Plants per age x accession group: {plants_per_group}
- Views per plant requested: {selected_views_per_plant}
- Rotational views per scan: {total_views}
"""


def _skeleton_reference(record: PackageRecord) -> str:
    """Render the skeleton section from the recorded node names.

    Deviation (task 8.3c). The vault script described the skeletons in prose that
    duplicated ``build_slp_project.py``'s constants, and nothing compared the two. These
    are the names the record carries, and ``validate_package`` requires the record to
    agree with the skeleton actually written into the ``.slp`` — so the description a
    labeler reads and the skeleton they open cannot disagree without failing validation.

    Args:
        record: The package record.

    Returns:
        One paragraph per root type, in the package's declared order.
    """
    paragraphs = []
    for root_type in record.metadata.root_types:
        nodes = list(record.skeletons[root_type])
        chain = " -> ".join(f"`{node}`" for node in nodes)
        # Annotate the ends the way the vault text did, without its per-crop wording.
        chain = chain.replace(f"`{nodes[0]}`", f"`{nodes[0]}` (base)", 1)
        if len(nodes) > 1:
            chain = f"{chain[: chain.rfind('`' + nodes[-1] + '`')]}`{nodes[-1]}` (tip)"
        paragraphs.append(
            f"**{root_type.capitalize()} root** ({len(nodes)} nodes): {chain}"
        )
    return "\n\n".join(paragraphs)


def _views_per_plant(manifest: pd.DataFrame) -> str:
    """Report views per plant honestly, including when plants differ.

    Deviation (task 8.3b). The vault script computed ``len(rows) // plant_count``, which
    is right only when every plant contributes the same number of views and otherwise
    reports a number no plant has. Unequal views are not hypothetical — a scan short of
    its rotation, or a widened re-selection, produces them.

    Args:
        manifest: The loaded manifest.

    Returns:
        The count, or a range when plants differ.
    """
    counts = manifest.groupby("plant_qr_code").size()
    low, high = int(counts.min()), int(counts.max())
    return str(low) if low == high else f"{low}-{high}"


def _accessions(manifest: pd.DataFrame, record: PackageRecord) -> str:
    """Render the accession names, failing if the record does not cover the manifest.

    Deviation (task 8.3a). The vault script carried a three-entry map of WEEP accessions
    and fell back to printing the numeric id for anything else, so a package from another
    experiment documented its accessions as numbers. The names are a human lookup against
    Bloom (design.md F2), so an unmapped id means the lookup was not done — which is a
    thing to fix before handing the package to a labeler, not to paper over.

    Args:
        manifest: The loaded manifest.
        record: The package record.

    Returns:
        The accession names, comma-separated, ordered by id.

    Raises:
        ValueError: If the manifest names an accession the record does not.
    """
    ids = sorted({str(value) for value in manifest["accession_id"]})
    unmapped = [i for i in ids if i not in record.accessions]
    if unmapped:
        raise ValueError(
            f"{MANIFEST_FILENAME} names accession id(s) {unmapped} that "
            f"{PACKAGE_METADATA_FILENAME} does not map to a name (it maps "
            f"{sorted(record.accessions)}). Accession names are looked up from Bloom by "
            "hand, so an unmapped id means the lookup is incomplete — a labeler would be "
            "handed a package documenting its genotypes as numbers."
        )
    return ", ".join(record.accessions[i] for i in ids)


def render_readme(package_dir: Path) -> Path:
    """Render ``README.md`` into a package directory from its own metadata.

    Args:
        package_dir: The package directory. Must already hold the metadata file, the
            manifest, and the curated images.

    Returns:
        The path written.

    Raises:
        FileNotFoundError: If the package metadata file is absent.
        ValueError: If the counts disagree, or if an accession is unmapped.
    """
    package_dir = Path(package_dir)
    record = read_package_metadata(package_dir)
    manifest = pd.read_csv(package_dir / MANIFEST_FILENAME)

    # Deviation (task 8.3b). The vault script globbed `images/*.jpg` for the number it
    # published while the manifest was the record of what should be there, so a dropped
    # image became a smaller number in the documentation and nothing else. Every count
    # below now comes from the manifest, and the numbers must already agree before any of
    # them is written down — the same rule `validate_package` runs, not a second copy.
    assert_counts_agree(package_dir, manifest, record)

    meta = record.metadata
    project_rows = "".join(
        f"| `{project_filename(record, root_type)}` | "
        f"{root_type.capitalize()} root predictions "
        f"({len(record.skeletons[root_type])} nodes: "
        f"{record.skeletons[root_type][0]}-{record.skeletons[root_type][-1]}) |\n"
        for root_type in meta.root_types
    )
    ages = sorted({int(age) for age in manifest["plant_age_days"]})
    text = _PREAMBLE.format(
        title=f"{meta.species.capitalize()} {meta.experiment.upper()} Labeling Package",
        species=meta.species,
        experiment=meta.experiment.upper(),
        images_dirname=IMAGES_DIRNAME,
        image_count=len(manifest),
        project_rows=project_rows,
        manifest_filename=MANIFEST_FILENAME,
        metadata_filename=PACKAGE_METADATA_FILENAME,
        readme_filename=README_FILENAME,
        first_project=project_filename(record, meta.root_types[0]),
        skeleton_reference=_skeleton_reference(record),
        bloom_experiment_id=record.bloom_experiment_id,
        plant_count=manifest["plant_qr_code"].nunique(),
        ages=", ".join(f"{age} DAG" for age in ages),
        accessions=_accessions(manifest, record),
        views_per_plant=_views_per_plant(manifest),
        seed=record.selection.seed,
        plants_per_group=record.selection.plants_per_group,
        selected_views_per_plant=record.selection.views_per_plant,
        total_views=record.selection.total_views,
    )
    path = package_dir / README_FILENAME
    path.write_text(text, encoding="utf-8")
    logger.info("Wrote README to %s", path)
    return path
